import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

import { useState } from "react";

export default function Home() {
  const [progress, setProgress] = useState(0);

  function handleProgress() {
    if (progress === 100) {
      setProgress(0);
    }
    setProgress((prevState) => prevState + 1);
  }

  // console.log(progress);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Footer />
        <Image
          src="/bg-simplify-section-desktop.svg"
          alt="alternative image"
          width={1439}
          height={360}
        />

        <section className="section">
          <div className="container">
            <h2>Hello Bulma</h2>
            <p className="subtitle is-3">
              My first website with <strong>Bulma</strong>!
            </p>
            <button className="delete is-large">Delete</button>
            <button
              className="button is-primary is-light"
              onClick={handleProgress}
            >
              Progress
            </button>
            <progress className="progress" value={progress} max="100">
              15%
            </progress>
          </div>
        </section>
      </main>
    </div>
  );
}
